name: "publish"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1

      - name: setup node.js enviornment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: publish
        run: npm publish --acesss public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
